import type { Metadata } from 'next'
import { K2D } from 'next/font/google'
import { AppContext } from '@/context'

import './globals.css'

const k2d = K2D({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-k2d',
  //display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='pl'>
      <body className={`${k2d.variable} antialiased`}>
        <AppContext>
          <div className='relative flex min-h-0 flex-grow flex-col'>
            {children}
          </div>
        </AppContext>
      </body>
    </html>
  )
}
